platform :ios do
    lane :prod do
        xcodeproj = "./ios/Photonic.xcodeproj"

        setup_ci
        app_store_connect_api_key
        match(
            type: 'appstore',
            readonly: is_ci,
            git_basic_authorization: Base64.strict_encode64("osamaqarem:#{ENV["GITHUB_TOKEN"]}")
        )
        increment_build_number(
            xcodeproj: xcodeproj,
            build_number: latest_testflight_build_number(initial_build_number: 1) + 1
        )
        update_code_signing_settings(
            use_automatic_signing: false,
            path: xcodeproj,
            code_sign_identity: ENV['sigh_com.osamaqarem.photonic_appstore_certificate-name'],
            profile_name: ENV['sigh_com.osamaqarem.photonic_appstore_profile-name'],
            build_configurations: "Release"
        )
        build_app(
            workspace: "./ios/Photonic.xcworkspace",
            scheme: "Photonic",
            configuration: "Release",
            export_method: "app-store"
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
end