platform :ios do
    lane :prod do
        xcodeproj = "./ios/Photonic.xcodeproj"

        setup_ci
        app_store_connect_api_key
        get_certificates
        get_provisioning_profile
        increment_build_number(
            xcodeproj: xcodeproj,
            build_number: latest_testflight_build_number(initial_build_number: 1) + 1
        )
        update_project_team(path: xcodeproj)
        build_app(
            workspace: "./ios/Photonic.xcworkspace",
            scheme: "Photonic",
            configuration: "Release",
            export_method: "app-store"
        )
        upload_to_testflight(skip_waiting_for_build_processing: true)
    end
end