# fly.toml app configuration file generated for photonic-remix on 2023-07-01T19:01:41+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "photonic-remix"
primary_region = "ams"

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# [deploy]
#   release_command = "bash ./scripts/migrate.sh"