name: Deploy Lambda

on:
  push:
    branches:
      - main
      - dev
    paths:
      - apps/lambda/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Add aws profile credentials to ~/.aws/credentials
        run: |
          aws configure set region eu-central-1 --profile photonic
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile photonic
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile photonic

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache-dependency-path: pnpm-lock.yaml
          cache: pnpm

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile
          cd apps/lambda/terraform
          terraform init

      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        working-directory: ./apps/lambda/terraform
        run: |
          terraform workspace select staging
          terraform apply --var-file=staging.tfvars -auto-approve

      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: ./apps/lambda/terraform
        run: |
          terraform workspace select production
          terraform apply --var-file=production.tfvars -auto-approve
