name: Lambda

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    # only build/deploy branch on pushes
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}

    steps:
      - name: Add aws profile credentials to ~/.aws/credentials
        run: |
          aws configure set region eu-central-1 --profile photonic
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile photonic
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile photonic

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Install dependencies
        run: yarn install --immutable --prefer-offline

      - name: Init Terraform
        working-directory: ./apps/lambda/terraform
        run: terraform init

      - name: Deploy
        if: ${{ github.ref == 'refs/heads/dev' }}
        id: deploy
        working-directory: ./apps/lambda/terraform
        run: |
          terraform apply --var-file=staging.tfvars -auto-approve
