name: Deploy Expo

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Fastlane
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install JS dependencies
        run: yarn install --immutable --prefer-offline

      - name: Prepare iOS
        env:
          STAGE: production
        run: |
          yarn app:prebuild
          cd apps/expo
          bundle install
          bundle exec pod install --project-directory=ios

      - name: Fastlane
        working-directory: apps/expo
        run: |
          bundle exec fastlane ios prod
