name: Deploy Expo

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install JS dependencies
        run: yarn install --immutable --prefer-offline --ignore-scripts

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          working-directory: apps/expo

      - name: Prebuild
        env:
          STAGE: production
        run: yarn expo prebuild

      - name: Pods Cache
        id: cache-pods
        uses: actions/cache@v3
        with:
          path: apps/expo/ios/Pods
          key: ${{ runner.os }}-pods

      - name: Install Pods
        working-directory: apps/expo
        env:
          STAGE: "production"
        run: bundle exec pod install --project-directory=ios

      - name: Run JS dependencies scripts
        run: yarn

      - name: Fastlane
        working-directory: apps/expo
        env:
          STAGE: "production"
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.FASTLANE_GITHUB_TOKEN }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_APP_IDENTIFIER: ${{ secrets.MATCH_APP_IDENTIFIER }}
          MATCH_TYPE: ${{ secrets.MATCH_TYPE }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_APP_IDENTIFIER: ${{ secrets.FASTLANE_APP_IDENTIFIER }}
          SPACESHIP_CONNECT_API_IN_HOUSE: ${{ secrets.SPACESHIP_CONNECT_API_IN_HOUSE }}
          FL_PROJECT_TEAM_ID: ${{ secrets.FL_PROJECT_TEAM_ID }}
          APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY_ID }}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY_KEY }}
        run: bundle exec fastlane ios prod
