name: Static Analysis

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - dev

jobs:
  Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: |
          yarn install --immutable --prefer-offline --ignore-scripts
          yarn patch-package --partial
          yarn postinstall

      - name: Staging Generate platform colors
        run: yarn expo platform-colors
        env:
          STAGE: development

      - name: Generate Production platform colors
        run: yarn expo platform-colors
        env:
          STAGE: production

      - name: Run checks
        run: yarn checks
