name: Static Analysis

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - dev

jobs:
  Pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache-dependency-path: pnpm-lock.yaml
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Staging Generate platform colors
        run: pnpm expo platform-colors
        env:
          STAGE: development

      - name: Generate Production platform colors
        run: pnpm expo platform-colors
        env:
          STAGE: production

      - name: Run checks
        run: pnpm checks
