name: Upload Cloudformation Template

on:
  push:
    branches:
      - main
      - dev
    paths:
      - apps/next/terraform/template_staging.json
      - apps/next/terraform/template_production.json
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - name: Add aws profile credentials to ~/.aws/credentials
        run: |
          aws configure set region eu-central-1 --profile photonic
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile photonic
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile photonic

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Init
        working-directory: apps/next/terraform
        run: terraform init

      - name: Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        working-directory: apps/next/terraform
        run: |
          terraform workspace select staging
          terraform apply --var-file=staging.tfvars -auto-approve

      - name: Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        working-directory: apps/next/terraform
        run: |
          terraform workspace select production
          terraform apply --var-file=production.tfvars -auto-approve
